openapi: 3.0.3
info:
  title: Looking For Group API
  version: 1.0.0
  description: |
    LFG API Documentation. This will showcase all the endpoints available and how to use them.
    Note: When accessed directly from the express app, the endpoints will have an additional "/api" prefix.
    Because of this, please use the vite proxy when reviewing the docs.
paths:
  # ADMIN
  /api/admin/promote:
    $ref: './paths/admin/promote.yaml'
  /api/admin/demote:
    $ref: './paths/admin/demote.yaml'
  /api/admin/tags:
    $ref: './paths/admin/tags.yaml'
  /api/admin/tags/{id}:
    $ref: './paths/admin/tags-id.yaml'
  /api/admin/skills:
    $ref: './paths/admin/skills.yaml'
  /api/admin/skills/{id}:
    $ref: './paths/admin/skills-id.yaml'
  /api/admin/status/{id}:
    $ref: './paths/admin/status.yaml'

  # DATASETS
  /api/datasets/majors/:
    $ref: './paths/datasets/majors.yaml'
  /api/datasets/mediums/:
    $ref: './paths/datasets/mediums.yaml'
  /api/datasets/roles/:
    $ref: './paths/datasets/roles.yaml'
  /api/datasets/skills/:
    $ref: './paths/datasets/skills.yaml'
  /api/datasets/socials/:
    $ref: './paths/datasets/socials.yaml'
  /api/datasets/tags/:
    $ref: './paths/datasets/tags.yaml'

  # Images
  /api/images/{image}::
    $ref: './paths/images.yaml'

  # ME

  # MOD
  /api/mod/user-report/{id}:
    $ref: './paths/mod/user-report.yaml'
  /api/mod/project-report/{id}:
    $ref: './paths/mod/project-report.yaml'
  /api/mod/bug-report/{id}:
    $ref: './paths/mod/bug-report-id.yaml'
  /api/mod/bug-report/:
    $ref: './paths/mod/bug-report.yaml'
  /api/mod/user-report/:
    $ref: './paths/mod/user-report.yaml'
  /api/mod/project-report/:
    $ref: './paths/mod/project-report.yaml'
  /api/mod/unban-user/{id}:
    $ref: './paths/mod/unban-user.yaml'
  /api/mod/notification:
    $ref: './paths/mod/notification.yaml'
  /api/mod/ban-user/{id}:
    $ref: './paths/mod/ban-user.yaml'
  /api/mod/delete-project/{id}:
    $ref: './paths/mod/delete-project.yaml'
  /api/mod/user-report/{id}/deactivate:
    $ref: './paths/mod/user-report-deactivate.yaml'
  /api/mod/clear-profile/{id}:
    $ref: './paths/mod/clear-profile.yaml'

# COMPONENTS
components:
  securitySchemes:
    shibbolethAuth:
      #Filler values need to be changed
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Role:
      $ref: 'schemas/datasets.yaml#/components/schemas/Role'
    Major:
      $ref: 'schemas/datasets.yaml#/components/schemas/Major'
    Tag:
      $ref: 'schemas/datasets.yaml#/components/schemas/Tag'
    Social:
      $ref: 'schemas/datasets.yaml#/components/schemas/Social'
    Skill:
      $ref: 'schemas/datasets.yaml#/components/schemas/Skill'
    Medium:
      $ref: 'schemas/datasets.yaml#/components/schemas/Medium'

    UserMember:
      $ref: 'schemas/users.yaml#/components/schemas/UserMember'
    UserSkill:
      $ref: 'schemas/users.yaml#/components/schemas/UserSkill'
    UserSocial:
      $ref: 'schemas/users.yaml#/components/schemas/UserSocial'
    ProjectFollowsList:
      $ref: 'schemas/users.yaml#/components/schemas/ProjectFollowsList'
    ProjectFollowing:
      $ref: 'schemas/users.yaml#/components/schemas/ProjectFollowing'
    UserFollowsList:
      $ref: 'schemas/users.yaml#/components/schemas/UserFollowsList'
    UserFollowing:
      $ref: 'schemas/users.yaml#/components/schemas/UserFollowing'
    UserPreview:
      $ref: 'schemas/users.yaml#/components/schemas/UserPreview'
    UserDetail:
      $ref: 'schemas/users.yaml#/components/schemas/UserDetail'
    BanDetail:
      $ref: 'schemas/users.yaml#/components/schemas/BanDetail'
    UserReport:
      $ref: 'schemas/users.yaml#/components/schemas/UserReport'
    BugReport:
      $ref: 'schemas/users.yaml#/components/schemas/BugReport'

    MySkill:
      $ref: 'schemas/me.yaml#/components/schemas/MySkill'
    MySocial:
      $ref: 'schemas/me.yaml#/components/schemas/MySocial'
    MyMajor:
      $ref: 'schemas/me.yaml#/components/schemas/MyMajor'
    MyFollowing:
      $ref: 'schemas/me.yaml#/components/schemas/MyFollowing'
    MyFollowsList:
      $ref: 'schemas/me.yaml#/components/schemas/MyFollowsList'
    MyProjectFollowing:
      $ref: 'schemas/me.yaml#/components/schemas/MyProjectFollowing'
    MyProjectFollowsList:
      $ref: 'schemas/me.yaml#/components/schemas/MyProjectFollowsList'
    MePreview:
      $ref: 'schemas/me.yaml#/components/schemas/MePreview'
    MeDetail:
      $ref: 'schemas/me.yaml#/components/schemas/MeDetail'
    MePrivate:
      $ref: 'schemas/me.yaml#/components/schemas/MePrivate'
    MyMember:
      $ref: 'schemas/me.yaml#/components/schemas/MyMember'

    ProjectImage:
      $ref: 'schemas/projects.yaml#/components/schemas/ProjectImage'
    ProjectMedium:
      $ref: 'schemas/projects.yaml#/components/schemas/ProjectMedium'
    ProjectFollowers:
      $ref: 'schemas/projects.yaml#/components/schemas/ProjectFollowers'
    ProjectFollower:
      $ref: 'schemas/projects.yaml#/components/schemas/ProjectFollower'
    ProjectMember:
      $ref: 'schemas/projects.yaml#/components/schemas/ProjectMember'
    ProjectMemberRequest:
      $ref: 'schemas/projects.yaml#/components/schemas/ProjectMemberRequest'
    ProjectSocial:
      $ref: 'schemas/projects.yaml#/components/schemas/ProjectSocial'
    ProjectTag:
      $ref: 'schemas/projects.yaml#/components/schemas/ProjectTag'
    ProjectJob:
      $ref: 'schemas/projects.yaml#/components/schemas/ProjectJob'
    ProjectPreview:
      $ref: 'schemas/projects.yaml#/components/schemas/ProjectPreview'
    ProjectDetail:
      $ref: 'schemas/projects.yaml#/components/schemas/ProjectDetail'
    ProjectWithFollowers:
      $ref: 'schemas/projects.yaml#/components/schemas/ProjectWithFollowers'
    ProjectVideo:
      $ref: 'schemas/projects.yaml#/components/schemas/ProjectVideo'
    ProjectReport:
      $ref: 'schemas/projects.yaml#/components/schemas/ProjectReport'

    UpdateUserInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/UpdateUserInput'
    AddUserSocialInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/AddUserSocialInput'
    UpdateUserSocialInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/UpdateUserSocialInput'
    AddUserSkillsInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/AddUserSkillsInput'
    UpdateUserSkillInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/UpdateUserSkillInput'
    AddUserMajorInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/AddUserMajorInput'
    CreateProjectInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/CreateProjectInput'
    UpdateProjectInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/UpdateProjectInput'
    CreateProjectImageInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/CreateProjectImageInput'
    UpdateProjectImageInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/UpdateProjectImageInput'
    ReorderProjectImagesInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/ReorderProjectImagesInput'
    CreateProjectMemberInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/CreateProjectMemberInput'
    UpdateProjectMemberInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/UpdateProjectMemberInput'
    AddProjectSocialInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/AddProjectSocialInput'
    UpdateProjectSocialInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/UpdateProjectSocialInput'
    AddProjectTagInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/AddProjectTagInput'
    UpdateProjectTagInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/UpdateProjectTagInput'
    AddProjectMediumsInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/AddProjectMediumsInput'
    CreateProjectJobInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/CreateProjectJobInput'
    UpdateProjectJobInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/UpdateProjectJobInput'
    CreateProjectVideoInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/CreateProjectVideoInput'
    CreateMemberRequestInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/CreateMemberRequestInput'
    TagWithIdInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/TagWithIdInput'
    TagInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/TagInput'
    SkillInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/SkillInput'
    AddUserReportInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/AddUserReportInput'
    AddProjectReportInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/AddProjectReportInput'
    BanUserInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/BanUserInput'
    ModeratorNotificationInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/ModeratorNotificationInput'
    AddBugReportInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/AddBugReportInput'
    UpdateBugReportInput:
      $ref: 'schemas/inputs.yaml#/components/schemas/UpdateBugReportInput'

    ErrorMessage:
      type: object
      properties:
        status:
          type: integer
          example: 500
        error:
          type: string
          example: Internal Server Error
        data:
          type: string
          nullable: true
          example: null
      required:
        - status
        - error
        - data

  responses:
    InternalServerError:
      description: An internal server error occurred
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
          examples:
            default:
              value:
                status: 500
                error: Internal Server Error
                data: null
    BadRequest:
      description: The request was invalid (e.g., malformed parameters)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
          examples:
            default:
              value:
                status: 400
                error: Invalid parameter(s)
                data: null
    NotFound:
      description: The requested resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
          examples:
            default:
              value:
                status: 404
                error: Not found
                data: null
    Unauthorized:
      description: Authentication is required and has failed or has not been provided
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
          examples:
            default:
              value:
                status: 401
                error: Unauthorized
                data: null
    Forbidden:
      description: Proper credentials have been provided, but such credentials are not authorized to access this resource.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
          examples:
            default:
              value:
                status: 409
                error: Forbidden
                data: null
    Conflict:
      description: Conflict to show resource already exists
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
          examples:
            default:
              value:
                status: 409
                error: Resource already exists
                data: null
